"""create faq schema with tags system

Revision ID: 66c2c105139c
Revises: 
Create Date: 2025-11-18 11:18:45.440820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c2c105139c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='사용자명'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='이메일'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='해시된 비밀번호'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='역할 (super_admin, admin, viewer)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='마지막 로그인 일시'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_is_active'), 'admin_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('intents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intent_id', sa.String(length=50), nullable=False, comment='CSV의 의도ID (예: INTacb567...)'),
    sa.Column('intent_type', sa.String(length=50), nullable=True, comment='의도 유형 (예: 질의응답)'),
    sa.Column('intent_name', sa.String(length=200), nullable=False, comment='의도명'),
    sa.Column('representative_question', sa.Text(), nullable=False, comment='대표 질의문'),
    sa.Column('display_question', sa.String(length=500), nullable=False, comment='화면 표시용 질의문'),
    sa.Column('answer', sa.Text(), nullable=False, comment='답변 내용'),
    sa.Column('context', sa.String(length=500), nullable=True, comment='컨텍스트 (추가 태그/키워드)'),
    sa.Column('usage_frequency', sa.Integer(), nullable=False, comment='사용 빈도'),
    sa.Column('question_count', sa.Integer(), nullable=False, comment='질의문 갯수'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='작성자'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intents_id'), 'intents', ['id'], unique=False)
    op.create_index(op.f('ix_intents_intent_id'), 'intents', ['intent_id'], unique=True)
    op.create_index(op.f('ix_intents_intent_name'), 'intents', ['intent_name'], unique=False)
    op.create_index(op.f('ix_intents_is_active'), 'intents', ['is_active'], unique=False)
    op.create_index(op.f('ix_intents_usage_frequency'), 'intents', ['usage_frequency'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='태그명 (예: #Ucloud, #Mail)'),
    sa.Column('description', sa.Text(), nullable=True, comment='태그 설명'),
    sa.Column('color', sa.String(length=7), nullable=True, comment='UI 표시 색상 (#RRGGBB)'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='표시 순서'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_is_active'), 'tags', ['is_active'], unique=False)
    op.create_table('faq_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intent_id', sa.Integer(), nullable=False, comment='의도 ID'),
    sa.Column('user_id', sa.String(length=50), nullable=True, comment='사용자 사번'),
    sa.Column('is_helpful', sa.Boolean(), nullable=False, comment='도움 여부 (True: 도움됨, False: 도움안됨)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='추가 의견'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_feedback_id'), 'faq_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_faq_feedback_intent_id'), 'faq_feedback', ['intent_id'], unique=False)
    op.create_table('intent_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intent_id', sa.Integer(), nullable=False, comment='의도 ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='태그 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_id', 'tag_id', name='uq_intent_tag')
    )
    op.create_index(op.f('ix_intent_tags_id'), 'intent_tags', ['id'], unique=False)
    op.create_index(op.f('ix_intent_tags_intent_id'), 'intent_tags', ['intent_id'], unique=False)
    op.create_index(op.f('ix_intent_tags_tag_id'), 'intent_tags', ['tag_id'], unique=False)
    op.create_table('question_variants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intent_id', sa.Integer(), nullable=False, comment='의도 ID'),
    sa.Column('question_text', sa.String(length=500), nullable=False, comment='질문 텍스트'),
    sa.Column('is_representative', sa.Boolean(), nullable=False, comment='대표 질의문 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_variants_id'), 'question_variants', ['id'], unique=False)
    op.create_index(op.f('ix_question_variants_intent_id'), 'question_variants', ['intent_id'], unique=False)
    op.create_index(op.f('ix_question_variants_question_text'), 'question_variants', ['question_text'], unique=False)
    op.create_table('search_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True, comment='사용자 사번'),
    sa.Column('search_query', sa.String(length=500), nullable=False, comment='검색어'),
    sa.Column('result_count', sa.Integer(), nullable=False, comment='검색 결과 수'),
    sa.Column('clicked_intent_id', sa.Integer(), nullable=True, comment='클릭한 의도 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['clicked_intent_id'], ['intents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_id'), 'search_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_logs_id'), table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_question_variants_question_text'), table_name='question_variants')
    op.drop_index(op.f('ix_question_variants_intent_id'), table_name='question_variants')
    op.drop_index(op.f('ix_question_variants_id'), table_name='question_variants')
    op.drop_table('question_variants')
    op.drop_index(op.f('ix_intent_tags_tag_id'), table_name='intent_tags')
    op.drop_index(op.f('ix_intent_tags_intent_id'), table_name='intent_tags')
    op.drop_index(op.f('ix_intent_tags_id'), table_name='intent_tags')
    op.drop_table('intent_tags')
    op.drop_index(op.f('ix_faq_feedback_intent_id'), table_name='faq_feedback')
    op.drop_index(op.f('ix_faq_feedback_id'), table_name='faq_feedback')
    op.drop_table('faq_feedback')
    op.drop_index(op.f('ix_tags_is_active'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_intents_usage_frequency'), table_name='intents')
    op.drop_index(op.f('ix_intents_is_active'), table_name='intents')
    op.drop_index(op.f('ix_intents_intent_name'), table_name='intents')
    op.drop_index(op.f('ix_intents_intent_id'), table_name='intents')
    op.drop_index(op.f('ix_intents_id'), table_name='intents')
    op.drop_table('intents')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_is_active'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
